fullnameOverride:  destination-lookup-reader
service:
  type: ClusterIP
  ports:
    http: 8080
istio:
  virtualService:
    gateways:
      - demis-gateway
    http:
      match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      retries:
        enable: true
        attempts: 0
        retryOn: null
    externalHttp:
      match:
      - uri:
         prefix: /destination-lookup/v1
      rewrite:
        uri: /
      retries:
        enable: true
        attempts: 0
        retryOn: null
    hosts: {}
  subsets:
    main:
      version: 1.0.0
      weight: "100"
# activate Traffic mirroring, also called shadowing with the following lines
#      mirror:
#        version: 1.1.0
#        mirrorPercentage: 0
